spring:
  application:
    name: forum-code-advisors
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: qwer
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true